conn c##_nbl_cc_txns_dm/"Welcome2018!";

CREATE TABLE "C##_NBL_CC_TXNS_DM"."RT_HIER_SNAP" 
   (	"MONTH_WID" CHAR(6 BYTE), 
	"EMPLOYEE_NUMBER" NUMBER(15,0), 
	"FIRST_NAME" VARCHAR2(450 BYTE), 
	"LAST_NAME" VARCHAR2(450 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(720 BYTE), 
	"NAME" VARCHAR2(2100 BYTE), 
	"SUPERVISOR_ID" NUMBER(10,0), 
	"REPORTS_TO_PATH" VARCHAR2(4000 BYTE), 
	"EXEC_MANAGER" VARCHAR2(4000 BYTE)
   )